version: '3.7'
services:
  db:
    image: postgres:17
    deploy:
      resources:
        limits:
          memory: 4g
    shm_size: '2gb'
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: P@ss@123@123
      POSTGRES_DB: postgres
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  odoo18:
    image: odoo:18
    deploy:
      resources:
        limits:
          memory: 4g
    shm_size: '2gb'
    depends_on:
      - db
    ports:
      - "10018:8069"
      - "20018:8072"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: P@ss@123@123
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always
