version: '3.7'
services:
  db:
    image: postgres:17
    deploy:
      resources:
        reservations:
          memory: 2G
        limits:
          memory: 4G
    shm_size: '2gb'
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo18@2024
      POSTGRES_DB: postgres
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  odoo18:
    image: odoo:18
    deploy:
      resources:
        reservations:
          memory: 2G
        limits:
          memory: 4G
    shm_size: '2gb'
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "10018:8069"
      - "20018:8072"
    tty: true
    command: --
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo18@2024
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always
  redis:
    image: redis:latest
    deploy:
      resources:
        reservations:
          memory: 2G
        limits:
          memory: 4G
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

